### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by msandersmontandon** [msandersmontandon/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create the index.html document
- [x] create the styles.css document
- [x] create the html skelleton 
- [x] create an elemente for the car image
- [x] make the css for the background
- [x] make the css for the starting position of the car
- [x] fix any bugs
- [x] clean up css
