### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by msandersmontandon** [msandersmontandon/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create the main.js document
- [x] create the data.js document
- [x] import the main.js script in the end of the body in the index.html document
- [x] make the css for each new position for the car
- [x] make the data model for the car, including properties for its orientation. Export it to the main.js
- [x] make the DOM object for the img element
- [x] add an envent listener for the key press
- [x] make the event handler that will apply the new css to the car img for the correct arrow press
- [x] fix any bugs
- [x] clean the css
