### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by msandersmontandon** [msandersmontandon/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] have the car position be absolute
- [x] have the data location store the pair x, y of the car current position
- [x] setInterval() for the car moving every 16ms when the space bar is pressed
- [x] have the callback function for the setInterval increment the x-axis position of the car
- [x] fix any bugs
- [x] clean up the css
